name: Docker

on:
  push:
    branches:
      - '*'
    tags:
      - v*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Echo sha
        id: sha
        run: echo "${{ env.GITHUB_SHA }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ikcap/demo-cd:latest

    outputs:
      sha: ${{ steps.build.outputs.sha }}

  update:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Check out k8s manifests
        uses: actions/checkout@v3
        if: github.event_name != 'pull_request'
        with:
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          repository: KnowledgeCaptureAndDiscovery/k8s
          path: './k8s'
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }} # `GH_PAT` is a secret that contains your PAT

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        if: github.event_name != 'pull_request'
        with:
          kustomize-version: "3.6.1"

      - name: Update Kubernetes resources
        if: github.event_name != 'pull_request'
        run: |
          cd k8s/disk-server/demo-cd
          kustomize edit set image demo-cd=ikcap/demo-cd:${{ needs.build.outputs.sha }}
          cat kustomization.yaml

      - name: Commit files
        if: github.event_name != 'pull_request'
        run: |
          cd k8s
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update demo"

      - name: Push changes
        if: github.event_name != 'pull_request'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "master"
          directory: k8s
