name: Docker

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - '*'
    tags:
      - v*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHA8: ${ GITHUB_SHA:8 }
    steps:

      - uses: actions/checkout@v2

      - name: Create value as an environment variable
        run: |
          echo "DOCKER_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Expose value 
        id: exposeValue
        run: |
          echo "::set-output name=docker_tag::${{ env.DOCKER_TAG }}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ikcap/demo-cd:${{ env.DOCKER_TAG }}

    outputs:
      docker_tag: ${{ steps.exposeValue.outputs.docker_tag }}


  update:
    needs: [build]
    runs-on: ubuntu-latest
    steps:

      - name: Check out k8s manifests
        uses: actions/checkout@v3
        if: github.event_name != 'pull_request'
        with:
          repository: KnowledgeCaptureAndDiscovery/k8s
          ref: master
          ssh-key: ${{ secrets.BOT_SSH }}
          persist-credentials: true

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        if: github.event_name != 'pull_request'
        with:
          kustomize-version: "3.6.1"

      - name: Update Kubernetes resources
        if: github.event_name != 'pull_request'
        run: |
          cd disk-server/demo-cd
          kustomize edit set image demo-cd=ikcap/demo-cd:${{ needs.build.outputs.docker_tag }}
  
          cat kustomization.yaml

      - name: Commit files
        if: github.event_name != 'pull_request'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update demo"

      - name: Push changes
        if: github.event_name != 'pull_request'
        uses: ad-m/github-push-action@master
        with:
          ssh: true
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "master"
          repository: KnowledgeCaptureAndDiscovery/k8s
