name: Example - Share output between jobs

on:
  push:

jobs:
  produce:

    runs-on: ubuntu-latest
    
    outputs:
      myValue: ${{ steps.exposeValue.outputs.myvalue }}

    steps:
      - uses: actions/checkout@v1
      - name: Expose value 
        id: exposeValue
        run: |
          echo "::set-output name=myvalue::${{ GITHUB_SHA }}"
            
  consume:

    runs-on: ubuntu-latest

    needs: produce
    
    steps:
      - uses: actions/checkout@v1
      - name: Use value
        run: |
          echo "${{ needs.produce.outputs.myvalue }}"
 
  
