name: Example - Share output between jobs

on:
  workflow_dispatch:

jobs:
  produce:

    runs-on: ubuntu-latest
    
    outputs:
      docker_tag: ${{ steps.exposeValue.outputs.myvalue }}

    steps:
      - uses: actions/checkout@v1
      - name: Create value as an environment variable
        run: |
          echo "DOCKER_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Expose value 
        id: exposeValue
        run: |
          echo "::set-output name=docker_tag::${{ env.DOCKER_TAG }}"
            
  consume:

    runs-on: ubuntu-latest

    needs: produce
    
    steps:
      - uses: actions/checkout@v1
      - name: Use value
        run: |
          echo "${{ needs.produce.outputs.docker_tag }}"
 
  
