name: Example - Share output between jobs

on:
  workflow_dispatch:

jobs:
  produce:

    runs-on: ubuntu-latest
    
    outputs:
      myValue: ${{ steps.exposeValue.outputs.myvalue }}

    steps:
      - uses: actions/checkout@v1
      - name: Expose value 
        id: exposeValue
        run: |
          echo "DOCKER_IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "::set-output name=myvalue::${{ env.DOCKER_IMAGE_TAG }}"
            
  consume:

    runs-on: ubuntu-latest

    needs: produce
    
    steps:
      - uses: actions/checkout@v1
      - name: Use value
        run: |
          echo "${{ needs.produce.outputs.DOCKER_IMAGE_TAG }}"
 
  
